### ISSUE TITLE
It doesn't change my password

### ISSUE THREAD

**Issue by HectorSaldes** [AlexisLoya/spring-roles#1]
Hello Sr. Developed, I have used your web application and until now all seem good, but when I created a new super admin, later I tried to change the password, and logout the session.

I tried to get my session again but with my new user, it didn't give me the session.

I think that it doesn't change my new password.

I hope your soon answer.

Evidences:

![image](https://user-images.githubusercontent.com/61708286/160983062-bb907054-4e63-4eb0-8d95-398c287ff94f.png)
![image](https://user-images.githubusercontent.com/61708286/160983099-735aca62-77e2-4b88-9aab-08694e1009c5.png)
![image](https://user-images.githubusercontent.com/61708286/160983134-5384db9a-ef5d-451b-b566-b1d74d336eae.png)
![image](https://user-images.githubusercontent.com/61708286/160983153-081f8748-578b-418a-9946-eac16005abb4.png)
![image](https://user-images.githubusercontent.com/61708286/160983179-fb0d4e41-26b1-438f-9c9b-3c8416ad8ec6.png)
![image](https://user-images.githubusercontent.com/61708286/160983193-b605c4eb-0eb1-4b68-8ea2-e051da189fcb.png)

**Comment by AlexisLoya** [comment]
I really appreciate the time of you got to describe the error. Tomorrow at morning I will be working on that

**Comment by AlexisLoya** [comment]
The feature is available now.
